# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: hello hapi CI

on:
  push:
    branches: main
  pull_request:
    branches: main
    
env:
  IMAGE_VER: v0.1
  
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm test
      - run: |
            echo $IMAGE_VER
            echo $IMAGE_VER-$GITHUB_RUN_ATTEMPT
      
  docker:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        env:
          IMAGE_TAG: ${{ env.IMAGE_VER }}-${{ GITHUB_RUN_ATTEMPT }}
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-hapi-ghaction:${{ env.IMAGE_VER }}-${{ GITHUB_RUN_ATTEMPT }},${{ secrets.DOCKERHUB_USERNAME }}/hello-hapi-ghaction:latest
    
