# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: hello hapi CI

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  IMAGE_VER: v0.1
  IMAGE_TAG: 0
  
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm test
      - run: |
              echo "github attempt:" $GITHUB_RUN_ATTEMPT
              echo "github number:" $GITHUB_RUN_NUMBER
              echo "using attempt number:" $IMAGE_VER-$GITHUB_RUN_ATTEMPT
              echo "using run number:" $IMAGE_VER-$GITHUB_RUN_NUMBER
      
  docker:
    needs: build-test
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}/hello-hapi-ghaction
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        # some how this env need to define here otherwise below image_tag ref to env.image_ver will throw error... yet to find the reason
        env: 
          IMAGE_TAG: ${{ env.IMAGE_VER }}-${{ github.run_number }}
        with:
          push: true
          tags: ${{ env.DOCKERHUB_REGISTRY }}:${{ env.IMAGE_TAG }},${{ env.DOCKERHUB_REGISTRY }}:latest

  trigger:
    needs: [build-test, docker]
    runs-on: ubuntu-latest
    steps:
        - 
          name: Repository Dispatch
          # this action is used for trigger external action in another repo and pass some vars. 
          # More ppl using this action although there are others actions similar to this
          uses: peter-evans/repository-dispatch@v3
          with:
            # create a PAT using the github UI for this account where this repo is under 
            # and add secret variable with name MY_GITHUB_ACTIONS_PAT (under hello-hapi-githubaction) 
            # with the generated token as value using the github UI
            token: ${{ secrets.MY_GITHUB_ACTIONS_PAT }}
            repository: chloongloong/hello-hapi-deployment-manifest-ghaction
            event-type: my-event
            client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "IMAGE_TAG": "${{ env.IMAGE_TAG }}"}'
    
